### 1. 注册一个用户名和密码
POST http://localhost:8080/register
Content-Type: application/json

{
  "username":"iot.technology",
  "password":"make-great"
}

### 2. 获取JWT
POST http://localhost:8080/authenticate
Content-Type: application/json

{
  "username":"iot.technology",
  "password":"make-great"
}

### 3. 请求/hello路径地址获取数据
GET http://localhost:8080/hello
Authorization: Bearer ...

