POST http://localhost:8080/api/v1/tsl
Content-Type: application/json

{
  "stringKey":"value1",
  "booleanKey":true,
  "doubleKey":42.0,
  "longKey":73,
  "jsonKey": {
    "someNumber": 42,
    "someArray": [1,2,3],
    "someNestedObject": {"key": "value"}
  }
}